#migration 1663251285_posts.sql
CREATE TABLE IF NOT EXISTS posts(
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    category_id BIGINT UNSIGNED,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    author_id BIGINT DEFAULT NULL,
    thumbnail TEXT,
    updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT author_id_fk FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE SET NULL
);
